### ISSUE TITLE
FT 01 US 01 - Visualizar publicações próprias

### ISSUE THREAD

**Issue by MartinsLucas** [UnbFeelings/unb-feelings-api#22]
Eu, como aluno, desejo visualizar as minhas publicações de sentimentos com o objetivo de recordar como me sinto.

**Critérios de Aceitação**
- [ ] Criar endpoint para enviar todos os meus Posts;
- [ ] Os Posts enviados podem conter: Sentimento, Texto e Hashtags;
- [ ] Documentar endpoints criados.

**Comment by fabio1079** [comment]
Branch: https://github.com/UnbFeelings/unb-feelings-api/tree/ft01_us01_user_posts
