### ISSUE TITLE
FT 01 US 03 - Visualizar publicações de sentimentos de uma disciplina

### ISSUE THREAD

**Issue by MartinsLucas** [UnbFeelings/unb-feelings-api#23]
Eu, como aluno, desejo visualizar as publicações de sentimentos de uma determinada disciplina, com o objetivo de entender seu impacto nos sentimentos dos alunos.

**Critérios de Aceitação**

- [x] Criar endpoint para enviar todos os Posts de uma determinada disciplina;
- [x] Os Posts enviados podem conter: Sentimento e Hashtags;
- [x] Documentar endpoints criados.

**Comment by marlonguimaraes** [comment]
Essa issue vai ser desenvolvida para facilitar o trabalho desta: https://github.com/UnbFeelings/unb-feelings-web-app/issues/21

**Comment by marlonguimaraes** [comment]
Critérios de aceitação cumpridos, porém o campo "tag" está como o id da tag, e não o conteúdo (texto) da mesma. Verificar o requisito pra ver se o desejado é o id ou o conteúdo.
