### ISSUE TITLE
FT 01 US 04 - Visualizar publicações de sentimentos de toda a universidade

### ISSUE THREAD

**Issue by MartinsLucas** [UnbFeelings/unb-feelings-api#24]
Eu, como aluno, desejo visualizar as publicações de sentimentos da UnB, com o objetivo de avaliar dos alunos universidade se sentem como um todo.

**Critérios de Aceitação**
- [ ] Criar endpoint para enviar todos os Posts;
- [ ] Os Posts enviados podem conter: Sentimento e Hashtags;
- [ ] Documentar endpoints criados.

**Comment by marceloabk** [comment]
Quando possível, adicionar data e hora que o post foi feito na API. Assim podemos montar os posts em formato de timeline.

**Comment by fabio1079** [comment]
Branch: https://github.com/UnbFeelings/unb-feelings-api/tree/ft01_us04_timeline
