### ISSUE TITLE
Criar fixture para popular as models do django

### ISSUE THREAD

**Issue by marlonguimaraes** [UnbFeelings/unb-feelings-api#32]
**Critério de aceitação**

- [ ] Pelo menos uma instância de cada model

**Comment by fabio1079** [comment]
https://github.com/UnbFeelings/unb-feelings-api/blob/develop/api/fixtures/api_initial_data.json

Só não tem Posts, Tags e Emotions

**Comment by MatheusRich** [comment]
@fabio1079 Essa issue já foi fechada, não?

**Comment by marlonguimaraes** [comment]
Fechando a issue, o PR inicial já foi "merged" aqui: https://github.com/UnbFeelings/unb-feelings-api/pull/39
