### ISSUE TITLE
Remodelar Emotion

### ISSUE THREAD

**Issue by fabio1079** [UnbFeelings/unb-feelings-api#37]
De acordo com nosso cliente, Emotion é "Boa" ou "Ruim", nada mais nada menos.
No nosso modelo atual Emotion está como uma relação NtoN(?) junto a Post o que se provou complicado demais para algo tão simples.
Então, a ação proposta é basicamente transformar a model Emotion e um simples campo(choice) em Post.

**No fancy stuff, keep it simple stupid !**

**Comment by MatheusRich** [comment]
@fabio1079 Acredito que o fato de existir uma Model pra Emotion é pelo fato de eu poder cadastrar diversas emoções diferentes pra uma escolha. Por exemplo:

- **Good**: "happy", "excited", "confident"
- **Bad**: "sad", "stressed", "tired"

Se a Model for transformada em apenas um campo, não seria possível cadastrar diversas emoções e ainda saber seu tipo (boa ou ruim).
