### ISSUE TITLE
Atualizar documentação da API

### ISSUE THREAD

**Issue by MatheusRich** [UnbFeelings/unb-feelings-api#48]
A documentação não bate com o que realmente acontece na API. Segue um exemplo (visualização de um post).

Documentação:
![image](https://user-images.githubusercontent.com/20938712/40396951-45bea30a-5e06-11e8-87f0-ac5d14b2b574.png)

Comportamento atual:

![image](https://user-images.githubusercontent.com/20938712/40396908-0dbaabb6-5e06-11e8-983b-f99ca2ea4afd.png)

**Comment by fabio1079** [comment]
## Na rota /posts/user/:id
Também seria interessante colocar na descrição que o campo "content" só vai ser exibido se o post pertencer ao usuário logado.
